[project]
name = "ai-homework1"
version = "0.1.0"
description = "BUPT 人工智能引论 聚类算法实验"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.1",
    "scikit-learn>=1.6.1",
]
